
    const Textl=[
         "Honesty is the practice of speaking and acting truthfully and with integrity, and it is essential to building trust and respect in our relationships. Whether it's being honest with ourselves and others about our thoughts and feelings, admitting our mistakes and shortcomings, or communicating clearly and transparently, honesty can create a sense of authenticity and connection in our interactions with others.",
         "Humility is the practice of recognizing our limitations and imperfections, and it is essential to personal growth and development. Whether it's acknowledging our mistakes and shortcomings, seeking feedback from others, or approaching new situations with a sense of openness and curiosity, humility can help us learn and grow in meaningful ways.  ",
         "One of the most important uses of technology in nature is the development of conservation tools. From wildlife tracking devices to habitat restoration techniques, we are constantly finding new ways to protect endangered species and their ecosystems. With the help of technology, we can make a real difference in the fight against extinction.  ",
         "Adaptability is the ability to adjust and thrive in changing circumstances, and it is essential to navigating the complexities of life. Whether it's adapting to new technologies, social norms, or personal challenges, adaptability allows us to stay resilient and flexible in the face of change.",
         "Resilience is the ability to bounce back from adversity and overcome challenges, and it is essential to maintaining our well-being and achieving our goals. Whether it's building our coping skills, seeking out support from loved ones, or taking time for self-care, resilience can help us navigate the ups and downs of life.",
         "The streets were empty and the air was thick with fog. It was as if the world had been put on pause, waiting for something to happen. As I walked through the quiet town, I couldn't help but feel a sense of unease. It was like I was the only one left in a ghost town.",
         "Forgiveness is a difficult but necessary act that can bring healing and peace to both the forgiver and the forgiven. Whether it's forgiving oneself or others, it's important to let go of grudges and resentments in order to move forward.",
         "The use of blockchain technology in sustainable supply chain management is another exciting development. Blockchain can be used to create more transparent and traceable supply chains, reducing the environmental and social impact of production and consumption.",
         "Empathy is the ability to understand and share the feelings of others, and it is essential to building strong and meaningful relationships. Whether it's actively listening to others' stories and experiences, expressing empathy and compassion towards their struggles, or offering support and encouragement, empathy can create a sense of connection and understanding between us and others.",
         "Respect is the practice of treating others with dignity and consideration, and it is essential to building positive and healthy relationships. Whether it's valuing others' perspectives and opinions, communicating with kindness and compassion, or practicing active listening, respect can create a sense of trust and mutual understanding in our interactions with others.",
         "Mindfulness is the practice of being present and fully engaged in the moment, and it is essential to cultivating a sense of peace and well-being. Whether it's through meditation, deep breathing, or simply taking time to savor the sights and sounds of the world around us, mindfulness can bring a sense of calm and clarity to our lives.",
         "Courage is the willingness to face our fears and take action despite the risks, and it is essential to achieving our goals and dreams. Whether it's standing up for what we believe in, pursuing our passions despite the obstacles, or taking bold and decisive action, courage can help us live our lives with purpose and intention.",
         "Compassion is the act of showing kindness, care, and concern for others, and it is essential to building a more just and equitable world. Whether it's standing up for the rights of marginalized communities or simply extending a helping hand to someone in need, compassion can make a positive impact in the world.",
         "One of the most exciting developments in technology and nature is the use of 3D printing. With 3D printing, we can create complex structures and objects using a variety of materials. This technology has the potential to revolutionize the way we think about manufacturing and waste reduction. By using 3D printing, we can create products that are more sustainable and environmentally friendly.",
         "The development of sustainable supply chain management systems is another important application of technology and nature. Sustainable supply chain management systems promote transparency and accountability in supply chains, reducing environmental and social impacts and promoting more responsible consumption and production practices."
] ;


export const getRandomText=()=>{
    return Textl[Math.floor(Math.random()*Textl.length)]
}